export const SET_AUTHORIZATION_TOKEN = 'SET_AUTHORIZATION_TOKEN'
export const SET_USER_EMAIL = 'SET_USER_EMAIL'
export const SET_USER_NAME = 'SET_USER_NAME'
export const SET_SNACKBAR = 'SET_SNACKBAR'
